version: "3.9"
services:
  api:
    image: ravidmasalton/events-api:0.1.0  
    build:
      context: .
    env_file:
      - .env  
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
